//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriticWeb.DataLayerEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class maxcriticEntities : DbContext
    {
        public maxcriticEntities()
            : base("name=maxcriticEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Award> Awards { get; set; }
        public virtual DbSet<Entertainment> Entertainments { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<GenreInEntertainment> GenreInEntertainments { get; set; }
        public virtual DbSet<Performer> Performers { get; set; }
        public virtual DbSet<PerformerInEntertainment> PerformerInEntertainments { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Song> Songs { get; set; }
        public virtual DbSet<SongInEntertainment> SongInEntertainments { get; set; }
        public virtual DbSet<UserCritic> UserCritics { get; set; }
    }
}
