//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriticWeb.DataLayerEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongInEntertainment
    {
        public System.Guid SongInEntertainmentId { get; set; }
        public System.Guid SongId { get; set; }
        public System.Guid EntertainmentId { get; set; }
    
        public virtual Entertainment Entertainment { get; set; }
        public virtual Song Song { get; set; }
    }
}
