//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriticWeb.App_Data.DataLayerEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Award
    {
        public System.Guid AwardId { get; set; }
        public Nullable<System.Guid> PerformerId { get; set; }
        public Nullable<System.Guid> EntertainmentId { get; set; }
        public string Name { get; set; }
        public string Nomination { get; set; }
        public System.DateTime Date { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Entertainment Entertainment { get; set; }
        public virtual Performer Performer { get; set; }
    }
}
