//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriticWeb.App_Data.DataLayerEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entertainment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entertainment()
        {
            this.Awards = new HashSet<Award>();
            this.GenreInEntertainments = new HashSet<GenreInEntertainment>();
            this.PerformerInEntertainments = new HashSet<PerformerInEntertainment>();
            this.Reviews = new HashSet<Review>();
            this.SongInEntertainments = new HashSet<SongInEntertainment>();
        }
    
        public System.Guid EntertainmentId { get; set; }
        public string EntertainmentType { get; set; }
        public string Name { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string Company { get; set; }
        public byte[] Poster { get; set; }
        public string Summary { get; set; }
        public string BuyLink { get; set; }
        public string MainLanguage { get; set; }
        public string Rating { get; set; }
        public string RatingComment { get; set; }
        public Nullable<int> MovieRuntimeMinute { get; set; }
        public string OfficialSite { get; set; }
        public string MovieCountries { get; set; }
        public Nullable<byte> TVSeason { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public string TrailerLink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Award> Awards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenreInEntertainment> GenreInEntertainments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformerInEntertainment> PerformerInEntertainments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SongInEntertainment> SongInEntertainments { get; set; }
    }
}
