//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriticWeb.App_Data.DataLayerEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenreInEntertainment
    {
        public System.Guid GenreInEntertainmentId { get; set; }
        public System.Guid EntertainmentId { get; set; }
        public System.Guid GenreId { get; set; }
    
        public virtual Entertainment Entertainment { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
