//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CriticWeb.App_Data.DataLayerEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Performer()
        {
            this.Awards = new HashSet<Award>();
            this.PerformerInEntertainments = new HashSet<PerformerInEntertainment>();
        }
    
        public System.Guid PerformerId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string PerformerType { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public byte[] Image { get; set; }
        public string Summary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Award> Awards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformerInEntertainment> PerformerInEntertainments { get; set; }
    }
}
